### ISSUE TITLE
What counts as MVS?

### ISSUE THREAD

**Issue by subascha** [IBM/count-mvs#13]
Hi there,

not really an issue but like you said nearly every log source is counting as MVS.

Is this definition a summary of an official document from IBM? I don't find any clear documentation on the IBM website about MVS.

Server log source over MSRPC - MVS (for me: yes)
Server log source over syslog - MVS (for me: yes)
Client log source over MSRPC - MVS? (for me: no)
Network device over syslog - MVS? (for me: no)

So what is defined as "virtual server"?

Hope you guys have an answer to this.

Best regards from Germany!

**Comment by jthomperoo** [comment]
Hi @subascha, we've completely rewritten this script and along with that updated the README to be a bit more comprehensive:

https://github.com/IBM/count-mvs/blob/main/README.md

Here's a bit of the README that I hope helps answer your question:

> ## What does MVS stand for?
> 
> MVS stands for Managed Virtual Server
> 
> ## What counts as an MVS?
> 
> MVS can be:
> 
> *  A physical or virtual server that can be seen by the environment e.g. Actual servers(Windows, Linux), VMs, EC2s
> 
> MVS can not be:
> 
> * An endpoint (laptop)
> * A SaaS service


Another point from a bit further down in the README may also be relevant:

> * If the setup has multiple domains a given IP could refer to multiple servers/machines. In this case if the same IP/hostname appears in multiple domains we count each occurance as a separate MVS i.e. if the same IP appeared in domain one and domain two that then counts as two MVS

Thanks!
