### ISSUE TITLE
Some FW and IDS are still in the list of MVS

### ISSUE THREAD

**Issue by nkuite** [IBM/count-mvs#17]
Hi,
My customer raised an issue because the script has some infra tools like Cisco Meraki  and DefensePro in the list of MVS. Is this normal?
thanks for your help
Gabriel

**Comment by jthomperoo** [comment]
Hi Gabriel,

This script treats anything that fits these definitions as MVS:
https://github.com/IBM/count-mvs#what-counts-as-an-mvs

> ## What counts as an MVS?
> 
> MVS can be:
> 
> *  A physical or virtual server that can be seen by the environment e.g. Actual servers(Windows, Linux), VMs, EC2s
> 
> MVS can not be:
> 
> * An endpoint (laptop)
> * A SaaS service

If these infra tools fit this definition they will be counted as MVS. A full list of what is being counted towards the MVS count is printed, so you can decide if the count needs to be tweaked afterwards.

Thanks,
Jamie.
