### ISSUE TITLE
Script breaks if log source identifier is too long

### ISSUE THREAD

**Issue by PatrickHemberger** [IBM/count-mvs#18]
Dear team,
get_device_ip function breaks if log source identifier is longer than 64 chars (without subdomain).

For some cloud integration we are using the unique resource identifier and resource names as log source identifier.
This can result in log source identifier >63 chars. If the log source identifier does not contain dots (subdomains) the get_device_ip function and the script fails with an uncaught exception.

Example:
```
>>> socket.gethostbyname('123456789012345678901234567890123456789012345678901234567890123')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
>>> socket.gethostbyname('1234567890123456789012345678901234567890123456789012345678901234')
Traceback (most recent call last):
  File "/usr/lib64/python3.6/encodings/idna.py", line 167, in encode
    raise UnicodeError("label too long")
UnicodeError: label too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)
```

**Comment by kiraitachi** [comment]
Having same issue on our environment as @PatrickHemberger mentioned. @jthomperoo could you take a look at this topic?

Thanks in advance!

**Comment by jthomperoo** [comment]
Hi to both of you, investigating this issue now.

**Comment by jthomperoo** [comment]
Able to recreate this with these steps:

1. Create a log source with an identifier with >63 characters, e.g `12345678901234567890123456789012345678901234567890123456789012345678901234567890`.
2. Make sure some events are pushed through that log source, alternatively update the `timestamp_last_seen` to be a timestamp within the last 24 hours.
3. Run the script.
4. It will fail to resolve with this error:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/encodings/idna.py", line 167, in encode
    raise UnicodeError("label too long")
UnicodeError: label too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./countMVS.py", line 1572, in <module>
    sys.exit(MVSProcessor().run())
  File "./countMVS.py", line 1556, in run
    self._generate_mvs_results(args)
  File "./countMVS.py", line 1544, in _generate_mvs_results
    log_source_processor = self._process_log_sources(log_sources)
  File "./countMVS.py", line 1498, in _process_log_sources
    log_source_processor.process_log_sources(log_sources, self.period_in_days)
  File "./countMVS.py", line 1240, in process_log_sources
    self._resolve_hostnames_to_ips()
  File "./countMVS.py", line 1152, in _resolve_hostnames_to_ips
    device_ip = IPParser.get_device_ip(machine_identifier)
  File "./countMVS.py", line 1039, in get_device_ip
    return socket.gethostbyname(hostname)
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)
```

The fix will be to gracefully handle this error, this is the most simple and robust solution, it should still work for these identifiers:

- IPv4 address.
- IPv6 address.
- A hostname.

A hostname must meet these requirements:
> Hostnames are composed of a sequence of [labels](https://en.wikipedia.org/wiki/DNS_label) concatenated with dots. For example, "en.wikipedia.org" is a hostname. Each label must be from 1 to 63 characters long. The entire hostname, including the delimiting dots, has a maximum of 253 [ASCII](https://en.wikipedia.org/wiki/ASCII) characters.
> From: https://en.wikipedia.org/wiki/Hostname#Syntax

So we can wrap that domain name resolution in a try-except block and log out any identifiers we can't resolve:

```python
try:
    device_ip = IPParser.get_device_ip(machine_identifier)
except:
    logging.info('Machine identifier %s is not resolvable to an ip address', machine_identifier)
    continue
```

And we should be able to look at the `/var/log/countMVS.log` file (or wherever it is configured to be written to) to see this message if this occurs:

```
2023-03-09 09:47:37,820 INFO Machine identifier 12345678901234567890123456789012345678901234567890123456789012345678901234567890 is not resolvable to an ip address
```
