### ISSUE TITLE
Script did not complete on a large deployment

### ISSUE THREAD

**Issue by nkuite** [IBM/count-mvs#23]
Hi,
My customer with more than 62,000 log sources try to run the script since April 14, 2023 3pm CET and the script is still running April 17, 2023 9am CET due to the embedded check for widows clients. The customer has around 10,000 Windows server log sources, but there is no windows client. Therefore the test for windows client is not necessary and was taking too much time to complete which is the reason why the customer stopped the script after almost 3 days.

1. Did you test the script on large deployment?
2. Can you include an option to bypass the check of windows clients?

Best regards

**Comment by robd2** [comment]
Hi @nkuite does the existing option below solve this?
-w, --skip-workstation-check

**Comment by nkuite** [comment]
Hi @robd2 
Yes, this will help because workstation check blocks the script to run at my customer with more than 10000 windows servers.
